[alias]
firmware = "build --release --target thumbv6m-none-eabi --features firmware --bin whitenoise"
flash = "run --release --target thumbv6m-none-eabi --features firmware --bin whitenoise"

[target.thumbv6m-none-eabi]
runner = "picotool load -v -x"

[env]
DEFMT_LOG = "info"
